In [48]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import plot_model
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import networkx as nx
%matplotlib inline

In [23]:
df = pd.read_csv('DSL-StrongPasswordData.csv')
df.head()

subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  \
0    s002             1    1    0.1491       0.3979       0.2488  0.1069   
1    s002             1    2    0.1111       0.3451       0.2340  0.0694   
2    s002             1    3    0.1328       0.2072       0.0744  0.0731   
3    s002             1    4    0.1291       0.2515       0.1224  0.1059   
4    s002             1    5    0.1249       0.2317       0.1068  0.0895   

   DD.t.i  UD.t.i     H.i  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.1674  0.0605  0.1169  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.1283  0.0589  0.0908  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.1291  0.0560  0.0821  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.2495  0.1436  0.1040  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.1676  0.0781  0.0903  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 34 columns]

In [24]:
subjects = df['subject'].unique()

In [25]:
subjects_to_int = {subject: i  for i, subject in enumerate(subjects)}
int_to_subjects = {i: subject for i, subject in enumerate(subjects)}

In [26]:
df = df.replace(subjects_to_int)

C:\Users\raahu\AppData\Local\Temp\ipykernel_15612\1725018810.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(subjects_to_int)


In [27]:
df.head()

subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  \
0        0             1    1    0.1491       0.3979       0.2488  0.1069   
1        0             1    2    0.1111       0.3451       0.2340  0.0694   
2        0             1    3    0.1328       0.2072       0.0744  0.0731   
3        0             1    4    0.1291       0.2515       0.1224  0.1059   
4        0             1    5    0.1249       0.2317       0.1068  0.0895   

   DD.t.i  UD.t.i     H.i  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.1674  0.0605  0.1169  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.1283  0.0589  0.0908  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.1291  0.0560  0.0821  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.2495  0.1436  0.1040  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.1676  0.0781  0.0903  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 34 columns]

In [28]:
data_raw = df.values
print(data_raw)
data_raw.shape

[[ 0.      1.      1.     ...  0.3509  0.2171  0.0742]
 [ 0.      1.      2.     ...  0.2756  0.1917  0.0747]
 [ 0.      1.      3.     ...  0.2847  0.1762  0.0945]
 ...
 [50.      8.     48.     ...  0.2017  0.0983  0.0905]
 [50.      8.     49.     ...  0.1917  0.0938  0.0931]
 [50.      8.     50.     ...  0.1993  0.1186  0.1018]]


(20400, 34)

In [29]:
data=data_raw[ :, 3:-1]
labels_raw = df['subject'].values
labels= labels_raw.reshape(labels_raw.shape[0],1)
data=np.hstack([data, labels])
print(data)

[[1.491e-01 3.979e-01 2.488e-01 ... 3.509e-01 2.171e-01 0.000e+00]
 [1.111e-01 3.451e-01 2.340e-01 ... 2.756e-01 1.917e-01 0.000e+00]
 [1.328e-01 2.072e-01 7.440e-02 ... 2.847e-01 1.762e-01 0.000e+00]
 ...
 [9.390e-02 1.189e-01 2.500e-02 ... 2.017e-01 9.830e-02 5.000e+01]
 [9.230e-02 1.294e-01 3.710e-02 ... 1.917e-01 9.380e-02 5.000e+01]
 [5.960e-02 1.310e-01 7.140e-02 ... 1.993e-01 1.186e-01 5.000e+01]]


In [30]:
np.random.shuffle(data)
x=data[ : , :-1]
y=data[:,-1]
x.shape

(20400, 30)

In [31]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

In [33]:
Y_train = to_categorical(y_train, num_classes=51)
Y_test=to_categorical(y_test,num_classes=51)


In [34]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_train.shape

(18360, 30, 1)

In [37]:
from tensorflow.keras.models import load_model

# Load the entire model from the file
rnn = load_model('LSTM.h5')
# rnn = load_model('')

In [45]:
print(X_test.shape)
predictions_prob= rnn.predict(X_test)
y_pred=[np.argmax(i) for i in predictions_prob]
print(y_pred)
print(y_test)

(2040, 30, 1)
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
[10, 19, 1, 16, 8, 17, 28, 25, 42, 24, 29, 14, 28, 22, 23, 19, 27, 9, 17, 6, 14, 17, 31, 15, 14, 10, 40, 3, 32, 26, 13, 24, 32, 37, 22, 20, 41, 30, 0, 26, 10, 47, 14, 23, 31, 29, 40, 35, 13, 43, 0, 28, 7, 17, 3, 13, 13, 29, 19, 12, 3, 30, 15, 2, 40, 41, 23, 12, 47, 35, 28, 18, 23, 30, 27, 18, 33, 28, 40, 43, 7, 31, 14, 41, 48, 26, 3, 44, 19, 4, 28, 19, 18, 19, 30, 19, 24, 36, 36, 3, 39, 10, 15, 25, 14, 16, 36, 33, 50, 45, 18, 3, 9, 10, 35, 31, 45, 14, 41, 1, 22, 0, 29, 1, 34, 27, 2, 22, 41, 14, 21, 0, 39, 30, 20, 29, 19, 22, 45, 44, 2, 50, 22, 12, 13, 21, 43, 39, 47, 23, 0, 30, 21, 12, 4, 12, 26, 6, 13, 35, 32, 4, 41, 7, 16, 23, 3, 21, 35, 13, 35, 2, 49, 28, 1, 13, 32, 39, 13, 36, 10, 42, 34, 18, 4, 15, 9, 11, 7, 40, 37, 26, 30, 5, 8, 10, 16, 18, 3, 24, 14, 29, 24, 36, 14, 45, 12, 9, 35, 47, 13, 40, 49, 48, 33, 42, 29, 24, 18, 32, 36, 11, 9, 42, 35, 27, 22, 35, 25, 18, 47, 35, 7, 9, 15, 42, 4, 38, 16, 29, 0, 45, 47, 38, 16, 8, 12, 5,

In [46]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
print("Accuracy: ",accuracy)
print("Precison: ",precision)
print("Recall: ",recall)
print("F1 Score: ",f1)

Accuracy:  0.9397058823529412
Precison:  0.940347262564436
Recall:  0.9402883774434289
F1 Score:  0.9393467846238395


In [53]:
plot_model(rnn, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

You must install pydot (`pip install pydot`) for `plot_model` to work.


In [54]:
plot_model(rnn, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

You must install pydot (`pip install pydot`) for `plot_model` to work.
