In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier 
import matplotlib.pyplot as plt  

C:\Users\skhim\AppData\Local\Temp\ipykernel_20580\1297645428.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df=pd.read_csv('DSL-StrongPasswordData.csv')

In [3]:
subjects = df['subject'].unique()

In [4]:
subjects_to_int = {subject: i  for i, subject in enumerate(subjects)}
int_to_subjects = {i: subject for i, subject in enumerate(subjects)}

In [5]:
df = df.replace(subjects_to_int)

C:\Users\skhim\AppData\Local\Temp\ipykernel_20580\1725018810.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(subjects_to_int)


In [6]:
df.head()

subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  \
0        0             1    1    0.1491       0.3979       0.2488  0.1069   
1        0             1    2    0.1111       0.3451       0.2340  0.0694   
2        0             1    3    0.1328       0.2072       0.0744  0.0731   
3        0             1    4    0.1291       0.2515       0.1224  0.1059   
4        0             1    5    0.1249       0.2317       0.1068  0.0895   

   DD.t.i  UD.t.i     H.i  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.1674  0.0605  0.1169  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.1283  0.0589  0.0908  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.1291  0.0560  0.0821  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.2495  0.1436  0.1040  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.1676  0.0781  0.0903  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 34 columns]

In [10]:
data_raw = df.values
print(data_raw)
data_raw.shape

[[ 0.      1.      1.     ...  0.3509  0.2171  0.0742]
 [ 0.      1.      2.     ...  0.2756  0.1917  0.0747]
 [ 0.      1.      3.     ...  0.2847  0.1762  0.0945]
 ...
 [50.      8.     48.     ...  0.2017  0.0983  0.0905]
 [50.      8.     49.     ...  0.1917  0.0938  0.0931]
 [50.      8.     50.     ...  0.1993  0.1186  0.1018]]


(20400, 34)

In [11]:
data=data_raw[ :, 3:-1]
labels_raw = df['subject'].values
labels= labels_raw.reshape(labels_raw.shape[0],1)
data=np.hstack([data, labels])
print(data)

[[1.491e-01 3.979e-01 2.488e-01 ... 3.509e-01 2.171e-01 0.000e+00]
 [1.111e-01 3.451e-01 2.340e-01 ... 2.756e-01 1.917e-01 0.000e+00]
 [1.328e-01 2.072e-01 7.440e-02 ... 2.847e-01 1.762e-01 0.000e+00]
 ...
 [9.390e-02 1.189e-01 2.500e-02 ... 2.017e-01 9.830e-02 5.000e+01]
 [9.230e-02 1.294e-01 3.710e-02 ... 1.917e-01 9.380e-02 5.000e+01]
 [5.960e-02 1.310e-01 7.140e-02 ... 1.993e-01 1.186e-01 5.000e+01]]


In [12]:
np.random.shuffle(data)
x=data[ : , :-1]
y=data[:,-1]
x.shape

(20400, 30)

In [15]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

In [22]:
training = [] 
test = [] 
scores = {} 

for k in range(1,20):
    clf = KNeighborsClassifier(n_neighbors = k) 
    clf.fit(X_train, y_train) 
    training_score = clf.score(X_train, y_train) 
    test_score = clf.score(X_test, y_test)
    print("K: ",k)
    print(training_score)
    print(test_score)
    training.append(training_score) 
    test.append(test_score) 
     



K:  1
1.0
0.7598039215686274
K:  2
0.8749455337690631
0.7279411764705882
K:  3
0.8721132897603486
0.7686274509803922
K:  4
0.8579520697167756
0.7681372549019608
K:  5
0.8502723311546841
0.7818627450980392
K:  6
0.8438997821350762
0.7813725490196078
K:  7
0.8407952069716775
0.7813725490196078
K:  8
0.835239651416122
0.7818627450980392
K:  9
0.8293028322440087
0.7794117647058824
K:  10
0.8247276688453159
0.7838235294117647
K:  11
0.822276688453159
0.7833333333333333
K:  12
0.8206427015250545
0.7803921568627451
K:  13
0.8167755991285403
0.7794117647058824
K:  14
0.8159041394335512
0.7774509803921569
K:  15
0.8124727668845316
0.7779411764705882
K:  16
0.8095315904139434
0.7857843137254902
K:  17
0.8088235294117647
0.782843137254902
K:  18
0.8047385620915033
0.7872549019607843
K:  19
0.8056644880174292
0.7843137254901961
