In [1]:
# Necessary imports 
import numpy as np 
import pandas as pd 
import xgboost as xgb
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

C:\Users\skhim\AppData\Local\Temp\ipykernel_16632\2118068402.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df=pd.read_csv('keystroke_data.csv')

In [3]:
subjects = df['name'].unique()

In [4]:
subjects_to_int = {subject: i  for i, subject in enumerate(subjects)}
int_to_subjects = {i: subject for i, subject in enumerate(subjects)}

In [5]:
df = df.replace(subjects_to_int)

C:\Users\skhim\AppData\Local\Temp\ipykernel_16632\1725018810.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(subjects_to_int)


In [6]:
# Drop backspaces and caps_lock column
df = df.drop(['backspaces', 'caps_lock'], axis=1)

In [7]:
df.head()

name  rep  H.period       H.t  DD.period.t  UD.period.t       H.i  \
0     0    1  0.092790  0.090883     0.246703     0.337586  0.087738   
1     0    2  0.087310  0.085243     0.304038     0.389281  0.097292   
2     0    3  0.130960  0.086942     0.329384     0.416326  0.093535   
3     0    4  0.140503  0.074106     0.361985     0.436090  0.094165   
4     0    5  0.147327  0.077649     0.291591     0.369241  0.109658   

     DD.t.i    UD.t.i       H.e  ...    UD.R.o       H.n    DD.o.n    UD.o.n  \
0  0.153798  0.241535  0.087737  ...  0.667031  0.172702  0.056452  0.229154   
1  0.217083  0.314374  0.102547  ...  0.552117  0.163859  0.061247  0.225106   
2  0.090715  0.184250  0.086722  ...  0.406839  0.108563  0.144304  0.252867   
3  1.971756  2.065921  0.109514  ...  0.655422  0.128880  0.126976  0.255856   
4  0.166732  0.276390  0.119945  ...  0.491701  0.150271  0.096402  0.246673   

        H.a    DD.n.a    UD.n.a       H.l    DD.a.l    UD.a.l  
0  0.154004  0.218646  0.372650  0.096280  0.171825  0.268105  
1  0.101477  0.194049  0.295526  0.101519  0.224497  0.326015  
2  0.176790  0.134659  0.311448  0.098133  0.156365  0.254498  
3  0.124415  0.244116  0.368531  0.084438  0.282270  0.366708  
4  0.154400  0.194311  0.348711  0.131821  0.163093  0.294914  

[5 rows x 30 columns]

In [8]:
data_raw = df.values
print(data_raw)
data_raw.shape

[[ 0.          1.          0.09279013 ...  0.09627986  0.17182493
   0.26810479]
 [ 0.          2.          0.08730984 ...  0.10151863  0.22449684
   0.32601547]
 [ 0.          3.          0.13095999 ...  0.09813261  0.15636539
   0.25449801]
 ...
 [ 0.          8.          0.07643366 ...  0.15189671  0.16237855
   0.31427527]
 [ 0.          9.          0.0811522  ...  0.11246324  0.17036772
   0.28283095]
 [ 0.         10.          0.06935549 ...  0.11066747  0.17479038
   0.28545785]]


(150, 30)

In [9]:
data=data_raw[ :, 2:]
labels_raw = df['name'].values
labels= labels_raw.reshape(labels_raw.shape[0],1)
data=np.hstack([data, labels])
print(data)

[[0.09279013 0.09088349 0.24670267 ... 0.17182493 0.26810479 0.        ]
 [0.08730984 0.08524323 0.30403805 ... 0.22449684 0.32601547 0.        ]
 [0.13095999 0.08694196 0.32938385 ... 0.15636539 0.25449801 0.        ]
 ...
 [0.07643366 0.06415033 0.25652361 ... 0.16237855 0.31427527 0.        ]
 [0.0811522  0.04557419 0.29244423 ... 0.17036772 0.28283095 0.        ]
 [0.06935549 0.07601428 0.26608658 ... 0.17479038 0.28545785 0.        ]]


In [10]:
np.random.shuffle(data)
x=data[ : , :-1]
y=data[:,-1]
x.shape

(150, 28)

In [ ]:
# scaler = MinMaxScaler()
# x = scaler.fit_transform(x)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

In [12]:

# Create an XGBoost classifier
model = xgb.XGBClassifier(objective='multi:softmax', num_class=2, random_state=0)

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         8
         1.0       1.00      1.00      1.00         7

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [13]:
x = [[0.081152201,0.045574188,0.292444229,0.338018417,0.074759722,0.120056152,0.194815874,0.086019278,1.517424822,1.603444099,0.062575817,0.551804543,0.61438036,0,-1709202964,-1709202964,0.17720294,1709202965,1709202965,0.104067564,0.124180317,0.228247881,0.101912022,0.059402227,0.161314249,0.112463236,0.170367718,0.282830954
]]
model.predict(x)

array([0])

In [14]:
model.predict([[0.063287735,0.084783792,0.381062508,0.4658463,0.038760185,0.202909231,0.241669416,0.066504478,0.471563578,0.538068056,0.035029888,0.732656717,0.767686605,-1709201385,0.929215431,-1709201384,0.089103222,0.209048271,0.298151493,0.07996726,0.295785666,0.375752926,0.1405406,0.208619356,0.349159956,0.036897659,0.156013489,0.192911148
]])

array([1])

In [15]:
model.predict([[0.087309837,0.085243225,0.304038048,0.389281273,0.097291708,0.2170825,0.314374208,0.10254693,0.166110277,0.268657207,0.078619003,0.940005064,1.018624067,0.102619648,0.583746433,0.686366081,0.112853527,0.439263821,0.552117348,0.163859129,0.061246634,0.225105762,0.101477146,0.194048643,0.295525789,0.101518631,0.224496841,0.326015472
]])

array([0])